export { default as DashboardLayout } from './DashboardLayout';
export { default as Landing } from './Landing';
export { default as HomeLayout } from './HomeLayout';
export { default as Register } from './Register';
export { default as Login } from './Login';
export { default as Error } from './Error';
export { default as Stats } from './Stats';
export { default as AllBasicInfos } from './AllBasicInfos';
export { default as AllUsers } from './AllUsers';
export { default as AllUsersMySQL } from './AllUsersMySQL';
export { default as AllUsersAzure } from './AllUsersAzure';
export { default as AddMedCase } from './AddMedCase';
export { default as AddBasicInfo } from './AddBasicInfo'
export { default as EditBasic } from './EditBasic';
export { default as EditUserMongo } from './EditUserMongo';
export { default as EditUserAzure } from './EditUserAzure';
export { default as EditUserMySQL } from './EditUserMySQL';
export { default as Profile } from './Profile';
export { default as Admin } from './Admin';