export { default as DashboardLayout } from './DashboardLayout';
export { default as Landing } from './Landing';
export { default as HomeLayout } from './HomeLayout';
export { default as Register } from './Register';
export { default as Login } from './Login';
export { default as Error } from './Error';
export { default as Stats } from './Stats';
export { default as AllJobs } from './AllJobs';
export { default as AllBasicInfos } from './AllBasicInfos';
export { default as DbsState } from './DbsState';
export { default as AddMedCase } from './AddMedCase';
export { default as AddBasicInfo } from './AddBasicInfo'
export { default as EditBasic } from './EditBasic';
export { default as Profile } from './Profile';
export { default as Admin } from './Admin';